# Tokenization

## Loading data

In [1]:
with open("../Data/L1.txt") as f:
    L1 = f.read()
data = L1[:1000]

In [2]:
print(data[:200])

Title: Alice's Adventures in Wonderland
Author: Lewis Carroll
Release date: June 27, 2008 [eBook #11]
                Most recently updated: November 10, 2024
Language: English
Credits: Arthur DiBianc


In [3]:
print(len(L1))

14871952


In [4]:
print(len(data))

1000


In [5]:
with open("../Data/L2.txt") as f:
    L2 = f.read()
data2 = L2[:1000]

In [6]:
print(len(L2))
print(len(data2))

25930805
1000


In [7]:
print(data2[:200])

=== Book 1 ===
The Declaration of Independence Of the United States Of America,

     NOTE:  This file combines the first two Project Gutenb


In [8]:
with open("../Data/L3.txt") as f:
    L3 = f.read()
data3 = L3[:1000]

In [9]:
print(len(L3))
print(len(data3))

26206426
1000


In [10]:
print(data3[:200])

URL: https://www.bbc.com/news/topics/c2vdnvdg6xxt
Palestinian paramedic Munther Abed rejects Israel's assertion that the vehicles approached troops with their lights off.
Many Palestinians say they ar


In [11]:
with open("../Data/L4.txt") as f:
    L4 = f.read()
data4 = L4[:1000]

In [12]:
print(len(L4))
print(len(data4))

18896924
1000


In [13]:
print(data4[:200])

=== The LLM Wears Prada: Analysing Gender Bias and Stereotypes through Online Shopping Data ===
Authors: Massimiliano Luca, Ciro Beneduce, Bruno Lepri, Jacopo Staiano
Published: 2025-04-02
URL: http:/


## EDA on Data

In [14]:
chars_l1 = sorted(list(set(L1)))
vocab_size_l1 = len(chars_l1)

In [15]:
print(vocab_size_l1)
print(''.join(chars_l1))

122
	
 !"#$&'()*,-./0123456789:;=?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_`abcdefghijklmnopqrstuvwxyz{}Š ¦°ÃÆÉàâäæçèéêïñòôöøùüœαβ–—‘’“”′″


In [16]:
chars_l2 = sorted(list(set(L2)))
vocab_size_l2 = len(chars_l2)

In [17]:
print(vocab_size_l2)
print(''.join(chars_l2))

164

 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ £Æ×àáâäåæçèéêëíïñóôöùûüāŒœΑΛΤΦέίαβγεηικλμνξοπρςστυωόύϰוחἰὁᾶ–—‘’“”…′


In [18]:
chars_l3 = sorted(list(set(L3)))
vocab_size_l3 = len(chars_l3)

In [19]:
print(vocab_size_l3)
print(''.join(chars_l3))

83

 "$%&'(),-./0123456789:=?ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz£É’…


In [20]:
chars_l4 = sorted(list(set(L4)))
vocab_size_l4 = len(chars_l4)

In [21]:
print(vocab_size_l4)
print(''.join(chars_l4))

1745
	
 !"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\]^_`abcdefghijklmnopqrstuvwxyz{|}~ ¡¢£¥§¨©«¬­®¯°±²³´µ¶·¸¹º»¿ÀÁÂÄÅÇÉÍÐÓÔÖ×ØÚÜßàáâãäåæçèéêëìíïñòóôõöøùúüýÿăąćČčďęěğıijŁłńňŒřśŞŠšţźżŽžƒǫˆˇˋ˘˙˚˛˜˝̸̂ΓΔΕΘΙΚΛΠΣΤΥΦΧΨΩήίαβγδεζηθικλμνξοπρςστυφχψωόύώϕϵПЧЪабвгдежзийклмнопрстуцчшыьєїاروڑیंइऔकगघजटठडतदधनपफबमयरलवसहाुेैॉोड़फ़।ংঅআউএকখগচটডতদধনবমযরহািুূে্ਂਅਓਕਗਚਜਟਣਤਦਧਨਪਫਬਮਰਲਵਸ਼ਸਹਾਿੀੁੂੇੈੋੱంఇఉఎకగచటడతదధనబమయరలవశసాిీుూేో్ขคงณดตทนบปผยรลวสหอะัำีุเแโใไ่้ᄀᄂᄃᄅᄇᄉᄋᄌᄏᄐᄑ하ᅢᅥᅩᅪᅬᅮᅳᅵᆨᆫᆯᆻᆼ  ​‌‐–—‘’‚“”„†‡•…
 ‰′‹€⃗⃝ℎℒℓℕℝ™ℱℳⅠⅡⅢⅳ←↑→↓↔↦↾⇐⇒⇓⇔∀∂∃∅∆∇∈∏∑−∗√∝∞∥∧∨∩∪∫∶∼≃≈≜≠≡≤≥≦≪≫≺≻⊂⊆⊓⊔⊕⊗⊙⊛⊢⊣⊤⊥⊲⋄⋅⋆⋉⋯⌈⌉⌊⌋⌢〉⎡⎣⎤⎦⎧⎨⎩⎪␣①②③④⑤⑥⑦⑧⑨■□▲△▶▷◇●◦♠♡♢♣♦♭♮✅✓✔✗✘✦❌❓❶❷❸❹❺❻⟨⟩⨁⩾、。《》【】いうえおがくこさしすただちつてでとなにのまもよらるをアィウスツデブメラㄴㄹ一万三上下不与丑专且世业东两严个中丹为主么义之也习书买乱了二于互五亚些交亮亲人什仅从他代以们价任份优会传但位住体何余作你使來例供保信個們候假做像儿元先克免兒入全公六共其典内再冗写军冠冬冰决况准凉出刀分切划则创判別利别到刷刺剂剃前剛剩副力功加动助勇化医十升单卖南博危即历原去又及友反发取变句另只召可台史号各合同名后向吗否吧含吸呀呃周命和咧品哎哥哧哪唱商問善喜嘛四回因国图圈國在地场均坐城基報境增墨士处复外多大天太央奇奏奖女她好如妙妨妹始姐委子字存学孩學它宇安完官宙定实客害家宾察實对對小少尝就层居展属山崇州工差己已巴巾币市帅师希带師帮常干平年并幸幹序应底店度开式引张弱当形影往很後得循微德必忐忑志忙快怕思性怪总息恼您情惊想愈意

In [22]:
import re
import emoji

# Define allowed character sets
english_regex = r"[a-zA-Z0-9\s]"  # English letters, numbers, spaces
math_symbols = r"[\+\-\*/=<>∑∫√πθΣ∂∞]"  # Add more math symbols if needed
special_chars = r"[\.,!?;:'\"()\[\]{}#@%^&*_~]"  # Common special chars

# Function to keep only emojis
def keep_emojis(text):
    return "".join(c for c in text if emoji.is_emoji(c))

# Remove non-English, non-math, non-special, and non-emoji characters
L4_cleaned = "".join(
    c for c in L4 if re.match(english_regex, c) or 
                    re.match(math_symbols, c) or 
                    re.match(special_chars, c) or 
                    emoji.is_emoji(c)
)

# Now, L4_cleaned holds the cleaned version of L4
print("✅ L4 cleaned and stored in L4_cleaned!")

✅ L4 cleaned and stored in L4_cleaned!


In [23]:
chars_l4 = sorted(list(set(L4_cleaned)))
vocab_size_l4 = len(chars_l4)

In [24]:
print(vocab_size_l4)
print(''.join(chars_l4))

126
	
 !"#%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[]^_abcdefghijklmnopqrstuvwxyz{}~ ©®Σθπ  
 ™↔∂∑√∞∫▶♠♣♦✅✔❌❓💊🔥😡🤬


## Tokenizing as charaters

In [36]:
# create a mapping from characters to integers
stoi_l1 = { ch:i for i,ch in enumerate(chars_l1) }
itos_l1 = { i:ch for i,ch in enumerate(chars_l1) }
encode_l1 = lambda s: [stoi_l1[c] for c in s] # encoder: take a string, output a list of integers
decode_l1 = lambda l: ''.join([itos_l1[i] for i in l]) # decoder: take a list of integers, output a string


In [37]:
print(encode_l1("Hii !! How are you"))

[37, 68, 68, 2, 3, 3, 2, 37, 74, 82, 2, 60, 77, 64, 2, 84, 74, 80]


In [38]:
print(decode_l1([37, 68, 68, 2, 3, 3, 2, 37, 74, 82, 2, 60, 77, 64, 2, 84, 74, 80]))

Hii !! How are you


In [39]:
# create a mapping from characters to integers
stoi_l2 = { ch:i for i,ch in enumerate(chars_l2) }
itos_l2 = { i:ch for i,ch in enumerate(chars_l2) }
encode_l2 = lambda s: [stoi_l2[c] for c in s] # encoder: take a string, output a list of integers
decode_l2 = lambda l: ''.join([itos_l2[i] for i in l]) # decoder: take a list of integers, output a string


In [40]:
print(encode_l2("Hii !! How are you"))

[41, 74, 74, 1, 2, 2, 1, 41, 80, 88, 1, 66, 83, 70, 1, 90, 80, 86]


In [41]:
print(decode_l2([41, 74, 74, 1, 2, 2, 1, 41, 80, 88, 1, 66, 83, 70, 1, 90, 80, 86]))

Hii !! How are you


In [42]:
# create a mapping from characters to integers
stoi_l3 = { ch:i for i,ch in enumerate(chars_l3) }
itos_l3 = { i:ch for i,ch in enumerate(chars_l3) }
encode_l3 = lambda s: [stoi_l3[c] for c in s] # encoder: take a string, output a list of integers
decode_l3 = lambda l: ''.join([itos_l3[i] for i in l]) # decoder: take a list of integers, output a string


In [43]:
print(encode_l3("Hii How are you ___https//"))

[33, 61, 61, 1, 33, 67, 75, 1, 53, 70, 57, 1, 77, 67, 73, 1, 52, 52, 52, 60, 72, 72, 68, 71, 12, 12]


In [44]:
print(decode_l3([33, 61, 61, 1, 33, 67, 75, 1, 53, 70, 57, 1, 77, 67, 73, 1, 52, 52, 52, 60, 72, 72, 68, 71, 12, 12]))

Hii How are you ___https//


In [65]:
# create a mapping from characters to integers
stoi_l4 = { ch:i for i,ch in enumerate(chars_l4) }
itos_l4 = { i:ch for i,ch in enumerate(chars_l4) }
encode_l4 = lambda s: [stoi_l4[c] for c in s] # encoder: take a string, output a list of integers
decode_l4 = lambda l: ''.join([itos_l4[i] for i in l]) # decoder: take a list of integers, output a string


In [66]:
print(encode_l4("Hii -!! How are you 🔥"))

[45, 76, 76, 6, 18, 7, 7, 6, 45, 82, 90, 6, 68, 85, 72, 6, 92, 82, 88, 6, 123]


In [64]:
print(decode_l4([45, 76, 76, 6, 18, 7, 7, 6, 45, 82, 90, 6, 68, 85, 72, 6, 92, 82, 88, 6, 123]))

Hii -!! How are you 🔥


## Train Test Split


In [48]:
import torch
import torch.nn as nn
from torch.nn import functional as F

In [53]:
# Train and test splits
data_l1 = torch.tensor(encode_l1(L1), dtype=torch.long)
n = int(0.9*len(data_l1)) # first 90% will be train, rest val
train_data_l1 = data_l1[:n]
val_data_l1 = data_l1[n:]

In [54]:
print(data_l1.shape,data_l1.dtype)

torch.Size([14871952]) torch.int64


In [55]:
print(data_l1[:500])

tensor([ 49,  68,  79,  71,  64,  26,   2,  30,  71,  68,  62,  64,   8,  78,
          2,  30,  63,  81,  64,  73,  79,  80,  77,  64,  78,   2,  68,  73,
          2,  52,  74,  73,  63,  64,  77,  71,  60,  73,  63,   1,  30,  80,
         79,  67,  74,  77,  26,   2,  41,  64,  82,  68,  78,   2,  32,  60,
         77,  77,  74,  71,  71,   1,  47,  64,  71,  64,  60,  78,  64,   2,
         63,  60,  79,  64,  26,   2,  39,  80,  73,  64,   2,  18,  23,  12,
          2,  18,  16,  16,  24,   2,  56,  64,  31,  74,  74,  70,   2,   5,
         17,  17,  57,   1,   2,   2,   2,   2,   2,   2,   2,   2,   2,   2,
          2,   2,   2,   2,   2,   2,  42,  74,  78,  79,   2,  77,  64,  62,
         64,  73,  79,  71,  84,   2,  80,  75,  63,  60,  79,  64,  63,  26,
          2,  43,  74,  81,  64,  72,  61,  64,  77,   2,  17,  16,  12,   2,
         18,  16,  18,  20,   1,  41,  60,  73,  66,  80,  60,  66,  64,  26,
          2,  34,  73,  66,  71,  68,  78,  67,   1,  32,  77,  

In [56]:
# Train and test splits
data_l2 = torch.tensor(encode_l2(L2), dtype=torch.long)
n = int(0.9*len(data_l2)) # first 90% will be train, rest val
train_data_l2 = data_l2[:n]
val_data_l2 = data_l2[n:]

In [57]:
print(data_l2.shape,data_l2.dtype)
print(data_l2[:500])

torch.Size([25930805]) torch.int64
tensor([30, 30, 30,  1, 35, 80, 80, 76,  1, 18,  1, 30, 30, 30,  0, 53, 73, 70,
         1, 37, 70, 68, 77, 66, 83, 66, 85, 74, 80, 79,  1, 80, 71,  1, 42, 79,
        69, 70, 81, 70, 79, 69, 70, 79, 68, 70,  1, 48, 71,  1, 85, 73, 70,  1,
        54, 79, 74, 85, 70, 69,  1, 52, 85, 66, 85, 70, 84,  1, 48, 71,  1, 34,
        78, 70, 83, 74, 68, 66, 13,  0, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
        30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
        30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,
        30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30,  0,  0,  1,  1,  1,
         1,  1, 47, 48, 53, 38, 27,  1,  1, 53, 73, 74, 84,  1, 71, 74, 77, 70,
         1, 68, 80, 78, 67, 74, 79, 70, 84,  1, 85, 73, 70,  1, 71, 74, 83, 84,
        85,  1, 85, 88, 80,  1, 49, 83, 80, 75, 70, 68, 85,  1, 40, 86, 85, 70,
        79, 67, 70, 83, 72,  0,  1,  1,  1,  1,  1, 71, 74, 77, 70, 84, 13,  1,
     

In [58]:
# Train and test splits
data_l3 = torch.tensor(encode_l3(L3), dtype=torch.long)
n = int(0.9*len(data_l3)) # first 90% will be train, rest val
train_data_l3 = data_l3[:n]
val_data_l3 = data_l3[n:]

In [59]:
print(data_l3.shape,data_l3.dtype)
print(data_l3[:500])

torch.Size([26206426]) torch.int64
tensor([46, 43, 37, 23,  1, 60, 72, 72, 68, 71, 23, 12, 12, 75, 75, 75, 11, 54,
        54, 55, 11, 55, 67, 65, 12, 66, 57, 75, 71, 12, 72, 67, 68, 61, 55, 71,
        12, 55, 15, 74, 56, 66, 74, 56, 59, 19, 76, 76, 72,  0, 41, 53, 64, 57,
        71, 72, 61, 66, 61, 53, 66,  1, 68, 53, 70, 53, 65, 57, 56, 61, 55,  1,
        38, 73, 66, 72, 60, 57, 70,  1, 26, 54, 57, 56,  1, 70, 57, 62, 57, 55,
        72, 71,  1, 34, 71, 70, 53, 57, 64,  6, 71,  1, 53, 71, 71, 57, 70, 72,
        61, 67, 66,  1, 72, 60, 53, 72,  1, 72, 60, 57,  1, 74, 57, 60, 61, 55,
        64, 57, 71,  1, 53, 68, 68, 70, 67, 53, 55, 60, 57, 56,  1, 72, 70, 67,
        67, 68, 71,  1, 75, 61, 72, 60,  1, 72, 60, 57, 61, 70,  1, 64, 61, 59,
        60, 72, 71,  1, 67, 58, 58, 11,  0, 38, 53, 66, 77,  1, 41, 53, 64, 57,
        71, 72, 61, 66, 61, 53, 66, 71,  1, 71, 53, 77,  1, 72, 60, 57, 77,  1,
        53, 70, 57,  1, 59, 67, 61, 66, 59,  1, 60, 73, 66, 59, 70, 77,  1, 53,
     

In [70]:
# Train and test splits
data_l4 = torch.tensor(encode_l4(L4_cleaned), dtype=torch.long)
n = int(0.9*len(data_l4)) # first 90% will be train, rest val
train_data_l4 = data_l4[:n]
val_data_l4 = data_l4[n:]

In [71]:
print(data_l4.shape,data_l4.dtype)
print(data_l4[:500])

torch.Size([18777665]) torch.int64
tensor([34, 34, 34,  6, 57, 75, 72,  6, 49, 49, 50,  6, 60, 72, 68, 85, 86,  6,
        53, 85, 68, 71, 68, 31,  6, 38, 81, 68, 79, 92, 86, 76, 81, 74,  6, 44,
        72, 81, 71, 72, 85,  6, 39, 76, 68, 86,  6, 68, 81, 71,  6, 56, 87, 72,
        85, 72, 82, 87, 92, 83, 72, 86,  6, 87, 75, 85, 82, 88, 74, 75,  6, 52,
        81, 79, 76, 81, 72,  6, 56, 75, 82, 83, 83, 76, 81, 74,  6, 41, 68, 87,
        68,  6, 34, 34, 34,  1, 38, 88, 87, 75, 82, 85, 86, 31,  6, 50, 68, 86,
        86, 76, 80, 76, 79, 76, 68, 81, 82,  6, 49, 88, 70, 68, 17,  6, 40, 76,
        85, 82,  6, 39, 72, 81, 72, 71, 88, 70, 72, 17,  6, 39, 85, 88, 81, 82,
         6, 49, 72, 83, 85, 76, 17,  6, 47, 68, 70, 82, 83, 82,  6, 56, 87, 68,
        76, 68, 81, 82,  1, 53, 88, 69, 79, 76, 86, 75, 72, 71, 31,  6, 23, 21,
        23, 26, 18, 21, 25, 18, 21, 23,  1, 58, 55, 49, 31,  6, 75, 87, 87, 83,
        31, 20, 20, 68, 85, 91, 76, 89, 19, 82, 85, 74, 20, 68, 69, 86, 20, 23,
     